version: 2.1
jobs:
  setup:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

workflows:
  version: 2
  build_only:
    jobs:
      - setup


