version: 2.1
jobs:
  setup:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run main.py
          command: |
            python main.py

workflows:
  version: 2
  build_and_run_hello:
    jobs:
      - setup


