version: 2.1
jobs:
  setup:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Run Tests
          command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup

